language: kotlin

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

matrix:
  fast_finish: true

#install: ./gradlew assemble --stacktrace
script:
  - ./gradlew check --stacktrace
  - ./gradlew assemble --stacktrace
  - ./gradlew publish -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'
    - '$HOME/.m2/repository/'

notifications:
  email: true